package cn.caitc.mapper;

import cn.caitc.entity.Tcalendar;
import cn.caitc.entity.TcalendarExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TcalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    long countByExample(TcalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    int deleteByExample(TcalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String dDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    int insert(Tcalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    int insertSelective(Tcalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    List<Tcalendar> selectByExample(TcalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    Tcalendar selectByPrimaryKey(String dDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Tcalendar record, @Param("example") TcalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Tcalendar record, @Param("example") TcalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tcalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calendar
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tcalendar record);
}